### ISSUE TITLE
Wondering if this still works

### ISSUE THREAD

**Issue by eelcocramer** [tayre/klv-decoder#5]
Hi,

Thanks a lot for sharing your repository.

I'm wondering if you believe this should still work. I tried running your code with the example video, but also with my own video, but it does not seem to get the KLV data from the stream. I tried adding some console logs to `DATA.prototype.getKLVValue` but (after rebuilding) the messages do not show in the log. So I'm wondering if I forgot something in my setup. I'm not quite sure how I can check the output stream to check if the KLV data is still present there or not.

I'm running ffmpeg from MacOS and I tried to use different browsers. Video is playing and map (showing video overlay) is showing.

Thanks,
Eelco

**Comment by eelcocramer** [comment]
So it seems to fail when [trying to find](https://github.com/tayre/klv-decoder/blob/master/app/src/jsmpeg/metadata.js#L30) the universal key here. I checked the byte array but there are only 0x0 values in there.

**Comment by eelcocramer** [comment]
Using firefox I do seem some logging. The sample video only has limited KLV data (or so it seems from my logging). Now I only need to figure out how to stream my own video so the player can pickup the KLV data.

**Comment by eelcocramer** [comment]
When I disable the CRC check in metadata.js I can see that the KLV meta is read from the sample video. However none of my own videos seem to work. The buffer only contains zero values so for some reason the KLV stream is not detected or read properly.

**Comment by niccellular** [comment]
I was able to get it to decode my stuff by applying the two PRs to the repo and rebuilding.

**Comment by martyrion** [comment]
> I was able to get it to decode my stuff by applying the two PRs to the repo and rebuilding.

Can you explain the process please? I am just learning JS and I have been struggling to make this work. Thanks!

**Comment by eelcocramer** [comment]
I've now also managed to get it to work.

Apparently the meta-data in my video streams used a different `streamid`. I tried changing the `streamid` using `ffmpeg` but this did not work. I ended up changing the value [here](https://github.com/tayre/klv-decoder/blob/master/app/src/jsmpeg/ts.js#L218) and set `PRIVATE_1` to `0xFC`.

Also in my case the KLV data was ignored because of a [failing `CRC` check](https://github.com/tayre/klv-decoder/blob/master/app/src/jsmpeg/metadata.js#L91) which I'm just ignoring for the moment.
